title: circumspectis documentation
description: documentation by Nurdan Turan and Berkay Olmaz
theme: just-the-docs

url: https://circumspectis-documentation.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
